image: node:22.11.0 # using 22.11.0 because the experimental feature for importing ESM (enabled by default starting with node 22.12.0) significantly slows test execution in the pipeline (https://github.com/vitest-dev/vitest/issues/7302)

options:
  max-time: 30

definitions:
  steps:
    - step: &lint-test-build
        name: Lint, tests and build
        caches:
          - node
        script:
          - cd org.knime.base.expressions/js-src
          - npm ci
          - npm run type-check
          - npm run ci:lint-format
          - npm run coverage
          - npm run audit
          - npm run build
        artifacts:
          - org.knime.base.expressions/js-src/dist/**

pipelines:
  pull-requests:
    "**":
      - step: *lint-test-build
  branches:
    '{master,releases/*}':
      - step: *lint-test-build
