image: node:18.19.0

options:
  max-time: 30

definitions:
  steps:
    - step: &lint-test-build
        name: Lint, tests and build
        caches:
          - node
        size: 2x # more memory to accomodate docker container for sonarcloud
        script:
          - git submodule update --init --recursive
          - cd org.knime.base.expressions/js-src
          - npm ci
          - npm run type-check
          - npm run ci:lint-format
          - npm run coverage
          - npm run audit
          - npm run build
        artifacts:
          - org.knime.base.expressions/js-src/dist/**

pipelines:
  pull-requests:
    "**":
      - step: *lint-test-build
  branches:
    '{master,releases/*}':
      - step: *lint-test-build
