[workspace]
channels = ["conda-forge"]
name = "expression-grammar"
platforms = ["win-64", "linux-64", "osx-64", "osx-arm64"]

[tasks]
dev = "antlr4-parse KnimeExpression.g4 fullExpr -tree"
build = "antlr4 -o ../org.knime.core.expressions/src/generated/java/org/knime/core/expressions/antlr -package org.knime.core.expressions.antlr -visitor KnimeExpression.g4"

[dependencies]
antlr4-tools = "*"
