export const MIN_WIDTH_FOR_SIDE_BY_SIZE_DESC_FUNC_CATALOG = 450;
export const MIN_WIDTH_FUNCTION_CATALOG = 220;
export const MAX_WIDTH_FUNCTION_CATALOG = 520;

export const SWITCH_TO_SMALL_DESCRIPTION = 1450;
export const WIDTH_OF_INPUT_OUTPUT_PANE = 300;
export const COMBINED_SPLITTER_WIDTH = 14;
