export const MIN_WIDTH_FOR_DISPLAYING_DESCRIPTION = 600;
export const MIN_WIDTH_FUNCTION_CATALOG = 300;

export const SWITCH_TO_SMALL_DESCRIPTION = 1450;
export const WIDTH_OF_INPUT_OUTPUT_PANE = 300;
export const COMBINED_SPLITTER_WIDTH = 14;
